---
# tasks file for roles/nginx_proxy
- name: 'Install Nginx on Public EC2'
  apt: 
    name: nginx
    update_cache: yes

- name: 'Disable the Default Virtual Host'
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent


- name: 'Create the Nginx Reverse Proxy'
  template:
    src: reverse-proxy.conf.j2
    dest: /etc/nginx/sites-available/reverse-proxy.conf
  notify: Restart Nginx service
  


- name: 'Create a symbolic link'
  file:
    src: /etc/nginx/sites-available/reverse-proxy.conf
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    state: link
  
