---
# tasks file for apache
- name: Install Apache
  apt: 
    name: apache2
    update_cache: yes

- name: Copy the template file to the remote server
  template:
    src: index.html.j2 
    dest: /var/www/html/index.html